/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as PortfolioRouteImport } from './routes/_portfolio'
import { Route as PageRouteImport } from './routes/_page'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as PortfolioIndexRouteImport } from './routes/_portfolio/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as PageGuide_mode_contrast_eleveeRouteImport } from './routes/_page/guide_mode_contrast_elevee'

const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/_portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/_page',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const PageGuide_mode_contrast_eleveeRoute =
  PageGuide_mode_contrast_eleveeRouteImport.update({
    id: '/guide_mode_contrast_elevee',
    path: '/guide_mode_contrast_elevee',
    getParentRoute: () => PageRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PortfolioIndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/guide_mode_contrast_elevee': typeof PageGuide_mode_contrast_eleveeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PortfolioIndexRoute
  '/guide_mode_contrast_elevee': typeof PageGuide_mode_contrast_eleveeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_page': typeof PageRouteWithChildren
  '/_portfolio': typeof PortfolioRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/_page/guide_mode_contrast_elevee': typeof PageGuide_mode_contrast_eleveeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/_portfolio/': typeof PortfolioIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/guide_mode_contrast_elevee'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guide_mode_contrast_elevee' | '/blog/$slug' | '/blog'
  id:
    | '__root__'
    | '/_page'
    | '/_portfolio'
    | '/blog'
    | '/_page/guide_mode_contrast_elevee'
    | '/blog/$slug'
    | '/_portfolio/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRouteWithChildren
  PortfolioRoute: typeof PortfolioRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portfolio': {
      id: '/_portfolio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page': {
      id: '/_page'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_portfolio/': {
      id: '/_portfolio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_page/guide_mode_contrast_elevee': {
      id: '/_page/guide_mode_contrast_elevee'
      path: '/guide_mode_contrast_elevee'
      fullPath: '/guide_mode_contrast_elevee'
      preLoaderRoute: typeof PageGuide_mode_contrast_eleveeRouteImport
      parentRoute: typeof PageRoute
    }
  }
}

interface PageRouteChildren {
  PageGuide_mode_contrast_eleveeRoute: typeof PageGuide_mode_contrast_eleveeRoute
}

const PageRouteChildren: PageRouteChildren = {
  PageGuide_mode_contrast_eleveeRoute: PageGuide_mode_contrast_eleveeRoute,
}

const PageRouteWithChildren = PageRoute._addFileChildren(PageRouteChildren)

interface PortfolioRouteChildren {
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRouteWithChildren,
  PortfolioRoute: PortfolioRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
