name: Deploy PROD

on:
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH et déploiement
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git checkout prod
            git pull origin prod
            npm install
            npm run build
            pm2 reload ${{ secrets.PM2_APP_NAME }}